language: java
jdk:
  - oraclejdk9
install:
  - wget -O aerospike-server.tgz https://www.aerospike.com/download/server/4.5.3.4/artifact/ubuntu14
  - tar xvzf aerospike-server.tgz
  - cd aerospike-server-community-4.5.3.4-ubuntu14.04
  - sudo ./asinstall
  - sudo service aerospike start
  - cd ..
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
